src/objects/Change_Request__c.object
<CustomObject>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>CR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CR_Step__c.object
<CustomObject>
    <description>Change Request Step</description>
    <fields>
        <fullName>Alternate_CR_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Alternate Step for any Decision Points</description>
        <inlineHelpText>Alternate Step for any Decision Points</inlineHelpText>
        <label>Alternate CR Step</label>
        <referenceTo>CR_Step__c</referenceTo>
        <relationshipLabel>CR Steps (Alternate CR Step)</relationshipLabel>
        <relationshipName>Alternate_CR_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change_Request__c</fullName>
        <label>Change Request</label>
        <referenceTo>Change_Request__c</referenceTo>
        <relationshipLabel>CR Steps</relationshipLabel>
        <relationshipName>CR_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dependent_CR_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Dependent CR Step -</description>
        <inlineHelpText>Dependent CR Step -</inlineHelpText>
        <label>Dependent CR Step</label>
        <referenceTo>CR_Step__c</referenceTo>
        <relationshipLabel>Dependent CR Steps</relationshipLabel>
        <relationshipName>Dependent_CR_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_CR_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Next CR Step - will be null for any Terminal Step</description>
        <inlineHelpText>Next CR Step - will be null for any Terminal Step</inlineHelpText>
        <label>Next CR Step</label>
        <referenceTo>CR_Step__c</referenceTo>
        <relationshipLabel>Next CR Step</relationshipLabel>
        <relationshipName>CR_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Owner__c</fullName>
        <description>Process Workflow Owner - in the Master Change Process from CSC</description>
        <inlineHelpText>Process Workflow Owner - in the Master Change Process from CSC</inlineHelpText>
        <label>Process Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Engineering</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_Step_Name__c</fullName>
        <description>Short Name of the CR Process Step</description>
        <inlineHelpText>Short Name of the Process Step</inlineHelpText>
        <label>Process Step Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Step_Type__c</fullName>
        <description>Each Process Steps can be Activity, Decision Point. Start, Terminal or Data collection point</description>
        <inlineHelpText>Each Process Steps can be Activity, Decision Point. Start, Terminal or Data collection point</inlineHelpText>
        <label>Step Type</label>
        <picklist>
            <picklistValues>
                <fullName>Starting Step</fullName>
                <color>#000099</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Activity Step</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminal Step</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Collection Point</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CR Step</label>
    <nameField>
        <displayFormat>CRP#{00000}</displayFormat>
        <label>CR Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CR Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ChangeRequestStepListController.cls
/**
* This controller is used as extension in CR Steps Diagram only.
*
* Author: Thanh Mai = tmai8@csc.com
* Date: 01/15/2013
*/
public class ChangeRequestStepListController {

    private Change_Request__c changeRequest;
    private List<CR_Step__c> crStepList;
    private Map<String, String> nextPointMap;
    private Map<String, String> alternatePointMap;
    
    public Change_Request__c getChangeRequest() {
        return this.changeRequest;
    }
    
    public Map<String, String> getNextPointMap() {
        return this.nextPointMap;
    }
    
    public Map<String, String> getAlternatePointMap() {
        return this.alternatePointMap;
    }
    
    public ChangeRequestStepListController(ApexPages.StandardController controller) {
        Change_Request__c workingChangeRequest = (Change_Request__c)controller.getRecord();
        this.changeRequest = [SELECT Id, Name, (SELECT Name, Step_Type__c, Process_Step_Name__c, 
                                                                Next_CR_Step__c, 
                                                                Alternate_CR_Step__c,
                                                                Dependent_CR_Step__c,
                                                                Status__c, Process_Owner__c
                                                FROM CR_Steps__r)
                              FROM Change_Request__c WHERE ID=:workingChangeRequest.Id];
        
        //Build the needed data for diagram.
        this.crStepList = this.changeRequest.CR_Steps__r;
        nextPointMap = this.buildNextPointMap(this.crStepList);
        alternatePointMap = this.buildAlternatePointMap(this.crStepList);
    }

    public List<CR_Step__c> getCRStepList() {
        return this.crStepList;
    }
    
    /** 
        * This is to build a map of next points in a change request.
        */
    private Map<String, String> buildNextPointMap(List<CR_Step__c> crStepList) {
        Map<String,String> returnMap = new Map<String,String>();
        for (CR_Step__c currentStep : crStepList) {
            List<CR_Step__c> stepList = [SELECT Id FROM CR_Step__c WHERE Name=:currentStep.Next_CR_Step__c];            
            if (stepList.size()>0) {
                returnMap.put(currentStep.Id, stepList.get(0).Id);
            }
        }
        return returnMap;
    }
    
    /** 
        * This is to build a map of alternate points in a change request.
        */
    private Map<String, String> buildAlternatePointMap(List<CR_Step__c> crStepList) {
        Map<String,String> returnMap = new Map<String,String>();
        for (CR_Step__c currentStep : crStepList) {
            List<CR_Step__c> stepList = [SELECT Id FROM CR_Step__c WHERE Name=:currentStep.Alternate_CR_Step__c];            
            if (stepList.size()>0) {
                returnMap.put(currentStep.Id, stepList.get(0).Id);
            }
        }
        return returnMap;
    }    
    
}