src/objects/Change_Request__c.object
<CustomObject>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>CR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CR_Step__c.object
<CustomObject>
    <description>Change Request Step</description>
    <fields>
        <fullName>Alternate_CR_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Alternate Step for any Decision Points</description>
        <inlineHelpText>Alternate Step for any Decision Points</inlineHelpText>
        <label>Alternate CR Step</label>
        <referenceTo>CR_Step__c</referenceTo>
        <relationshipLabel>CR Steps (Alternate CR Step)</relationshipLabel>
        <relationshipName>Alternate_CR_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change_Request__c</fullName>
        <label>Change Request</label>
        <referenceTo>Change_Request__c</referenceTo>
        <relationshipLabel>CR Steps</relationshipLabel>
        <relationshipName>CR_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Comments Entered upon completion of the process</description>
        <inlineHelpText>Comments Entered upon completion of the process</inlineHelpText>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Feed_Text__c</fullName>
        <description>Any Text Entered here will be used for Chatter Feed along with the Activity Name</description>
        <inlineHelpText>Any Text Entered here will be used for Chatter Feed along with the Activity Name</inlineHelpText>
        <label>Feed Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_CR_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Next CR Step - will be null for any Terminal Step</description>
        <inlineHelpText>Next CR Step - will be null for any Terminal Step</inlineHelpText>
        <label>Next CR Step</label>
        <referenceTo>CR_Step__c</referenceTo>
        <relationshipLabel>Next CR Step</relationshipLabel>
        <relationshipName>CR_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Owner__c</fullName>
        <description>Process Workflow Owner - in the Master Change Process from CSC</description>
        <inlineHelpText>Process Workflow Owner - in the Master Change Process from CSC</inlineHelpText>
        <label>Process Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Engineering</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_Step_Name__c</fullName>
        <description>Short Name of the CR Process Step</description>
        <inlineHelpText>Short Name of the Process Step</inlineHelpText>
        <label>Process Step Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Step_Type__c</fullName>
        <description>Each Process Steps can be Activity, Decision Point. Start, Terminal or Data collection point</description>
        <inlineHelpText>Each Process Steps can be Activity, Decision Point. Start, Terminal or Data collection point</inlineHelpText>
        <label>Step Type</label>
        <picklist>
            <picklistValues>
                <fullName>Starting Step</fullName>
                <color>#000099</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Activity Step</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminal Step</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Collection Point</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CR Step</label>
    <nameField>
        <displayFormat>CRP#{00000}</displayFormat>
        <label>CR Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CR Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CRStepsDiagramTestController.cls
public with sharing class CRStepsDiagramTestController {
   
   private List<String> processOwnerList = new List<String>();
   
   private List<CR_Step__c> listOwnerStep;
   
   private Map<String, List<CR_Step__c>> mapProcessOwner = new Map<String, List<CR_Step__c>>();
    
   public Change_Request__c changeRequest{
        get {
            if (changeRequest == null)
                changeRequest = new Change_Request__c();
            return changeRequest;
        }
        
        set;    
   }
   
   // Default contructor
   public CRStepsDiagramTestController(){
       String changeRequestId = changeRequest.Id;
       
       // Get all process owner type
       list<SelectOption> testOptions =  ASNUtils.getPicklistValues(new CR_Step__c(), 'Process_Owner__c');
       
       for(SelectOption optionId : testOptions){
           processOwnerList.add(optionId.getLabel());
       }
   }
    
   public List<String> getProcessOwnerList(){
       return this.processOwnerList;
   }
   
   public List<CR_Step__c> getListOwnerStep(String processOwnerName){
       List<CR_Step__c> stepList = [SELECT c.Process_Owner__c, c.Step_Type__c, c.Status__c, c.Process_Step_Name__c, c.Next_CR_Step__c, c.Name, c.Id, c.Feed_Text__c, c.Comments__c, c.Change_Request__c, c.Alternate_CR_Step__c FROM CR_Step__c c WHERE c.Process_Owner__c=:processOwnerName];
       
       return stepList;
   }
   
   public Map<String, List<CR_Step__c>> getMapProcessOwner(){
       for(String proOwnName: processOwnerList){
           mapProcessOwner.put(proOwnName, getListOwnerStep(proOwnName));
       }
       return mapProcessOwner;
   }
    
}