src/objects/Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Chage_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>CR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CR_Participant__c.object
<CustomObject>
    <description>Participants for this change -  A subset of Project Participants</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CR Participants</relationshipLabel>
        <relationshipName>CR_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Chage_Request__c</fullName>
        <label>Chage Request</label>
        <referenceTo>Change_Request__c</referenceTo>
        <relationshipLabel>CR Participants</relationshipLabel>
        <relationshipName>CR_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CR Participant</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CR Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CR_Step__c.object
<CustomObject>
    <description>Change Request Step</description>
    <fields>
        <fullName>Alternate_CR_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Alternate Step for any Decision Points</description>
        <inlineHelpText>Alternate Step for any Decision Points</inlineHelpText>
        <label>Alternate CR Step</label>
        <referenceTo>CR_Step__c</referenceTo>
        <relationshipLabel>CR Steps (Alternate CR Step)</relationshipLabel>
        <relationshipName>Alternate_CR_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change_Request__c</fullName>
        <label>Change Request</label>
        <referenceTo>Change_Request__c</referenceTo>
        <relationshipLabel>CR Steps</relationshipLabel>
        <relationshipName>CR_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dependent_CR_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Dependent CR Step -</description>
        <inlineHelpText>Dependent CR Step -</inlineHelpText>
        <label>Dependent CR Step</label>
        <referenceTo>CR_Step__c</referenceTo>
        <relationshipLabel>Dependent CR Steps</relationshipLabel>
        <relationshipName>Dependent_CR_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_CR_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Next CR Step - will be null for any Terminal Step</description>
        <inlineHelpText>Next CR Step - will be null for any Terminal Step</inlineHelpText>
        <label>Next CR Step</label>
        <referenceTo>CR_Step__c</referenceTo>
        <relationshipLabel>Next CR Step</relationshipLabel>
        <relationshipName>CR_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Owner__c</fullName>
        <description>Process Workflow Owner - in the Master Change Process from CSC</description>
        <inlineHelpText>Process Workflow Owner - in the Master Change Process from CSC</inlineHelpText>
        <label>Process Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Engineering</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_Step_Name__c</fullName>
        <description>Short Name of the CR Process Step</description>
        <inlineHelpText>Short Name of the Process Step</inlineHelpText>
        <label>Process Step Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Step_Type__c</fullName>
        <description>Each Process Steps can be Activity, Decision Point. Start, Terminal or Data collection point</description>
        <inlineHelpText>Each Process Steps can be Activity, Decision Point. Start, Terminal or Data collection point</inlineHelpText>
        <label>Step Type</label>
        <picklist>
            <picklistValues>
                <fullName>Starting Step</fullName>
                <color>#000099</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Activity Step</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminal Step</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Collection Point</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CR Step</label>
    <nameField>
        <displayFormat>CRP#{00000}</displayFormat>
        <label>CR Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CR Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>Project information - functions as the root object of all ASN Activities</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Project Status</description>
        <inlineHelpText>Project Status</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#000099</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Participant__c.object
<CustomObject>
    <description>All Vendors participating in this project</description>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Participants</relationshipLabel>
        <relationshipName>Project_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area_Of_Expertise__c</fullName>
        <label>Area Of Expertise</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <label>Project ID</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Participants</relationshipLabel>
        <relationshipName>Project_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Tier__c</fullName>
        <label>Project Tier</label>
        <picklist>
            <picklistValues>
                <fullName>OEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Participant</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Project Participants</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ChangeRequestFlow2Controller.cls
/**
* This controller is used as extension in CR Steps Diagram only.
*
* Author: Thanh Mai = tmai8@csc.com
* Date: 01/15/2013
* 
* Edited by Han Nguyen
*/
public class ChangeRequestFlow2Controller {

    private Change_Request__c changeRequest;
    private List<CR_Step__c> crStepList;
    private Map<String, CR_Step__c> crStepMap;
    private String startingStepName;
    
    private Project__c project;
    private List<ProjectParticipantWrapper> projParticipantWrapperList;
    private List<CR_Participant__c> newCrParticipantList; 
    private Boolean nextStep = true;
    
    private integer numOfClientStep = 0;
    private integer numOfPCStep = 0;
    private integer numOfPEStep = 0;
    private integer numOfSPMStep = 0;
    private integer numOfSCStep = 0;
    private integer numOfSEStep = 0;

    public Change_Request__c getChangeRequest() {
        return this.changeRequest;
    }
    
    public String getStartingStepName() {
        startingStepName = 'CRP#00016'; //have starting step type?
        return this.startingStepName;
    } 
    
    public Map<String, CR_Step__c> getCRStepMap() {
        return this.crStepMap;
    }
    
    public ChangeRequestFlow2Controller (ApexPages.StandardController controller) {
        Change_Request__c workingChangeRequest = (Change_Request__c)controller.getRecord();
        this.changeRequest = [SELECT Id, Name, Project__c, (SELECT Name, Step_Type__c, Process_Step_Name__c, 
                                                                Next_CR_Step__c, 
                                                                Alternate_CR_Step__c,
                                                                Dependent_CR_Step__c,
                                                                Status__c, Process_Owner__c
                                                FROM CR_Steps__r)
                              FROM Change_Request__c WHERE ID=:workingChangeRequest.Id];
                              
        this.project = [SELECT Id, (SELECT Name, Account_ID__c, Area_Of_Expertise__c, Project_Tier__c
                                    FROM Project_Participants__r)
                                                
                        FROM Project__c WHERE ID=:changeRequest.Project__c];
        
        //Build the needed data for diagram.
        this.crStepList = this.changeRequest.CR_Steps__r;
        this.crStepList.sort();
      
        countOwerTypeSteps(this.crStepList);
        this.crStepMap = buildCRStepMap(this.crStepList);
        //alternatePointMap = this.buildAlternatePointMap(this.crStepList);
        
        //build a list of project participant wrappers
        this.projParticipantWrapperList= buildProjectParticipantWrapperList(this.project.Project_Participants__r);
        this.nextStep = true;
    }

    public List<CR_Step__c> getCRStepList() {
        return this.crStepList;
    }
   
    /** 
        * This is to build a map of next points in a change request.
        */
    private Map<String, CR_Step__c> buildCRStepMap(List<CR_Step__c> crStepList) {
        Map<String,CR_Step__c> returnMap = new Map<String,CR_Step__c>();
        for (CR_Step__c currentStep : crStepList) {           
                returnMap.put(currentStep.Name, currentStep);
        }
        return returnMap;
    }
    
       
    private void countOwerTypeSteps(List<CR_Step__c> crStepList) {
        for(CR_Step__c step: crStepList) {
            if (step.Process_Owner__c == 'Client')  
                numOfClientStep++;
            else if (step.Process_Owner__c == 'Prime Commercial')  
                numOfPCStep++;
            else if (step.Process_Owner__c == 'Prime Engineering')  
                numOfPEStep++;
            else if (step.Process_Owner__c == 'SPM')  
                numOfSPMStep++;
            else if (step.Process_Owner__c == 'Sub Commercial')  
                numOfSCStep++;
            else if (step.Process_Owner__c == 'Sub Engineering')  
                numOfSEStep++;   
                                
        }        
    }
     public integer getNumOfClientStep() {
         return numOfClientStep; 
      }
    public integer getNumOfPCStep() {
         return numOfPCStep; 
      }
    public integer getNumOfPEStep() {
         return numOfPEStep; 
      }
    public integer getNumOfSPMStep() {
         return numOfSPMStep; 
      }
    public integer getNumOfSCStep() {
         return numOfSCStep; 
      }
    public integer getNumOfSEStep() {
         return numOfSEStep; 
      }        
   
   /** 
      * Build a list of Project Participant Wrappers
      */
   private List<ProjectParticipantWrapper> buildProjectParticipantWrapperList(List<Project_Participant__c> projParticipantList){
       List<ProjectParticipantWrapper> pPWList = new List<ProjectParticipantWrapper>();
       for(Project_Participant__c pp : projParticipantList){
           pPWList.add(new ProjectParticipantWrapper(pp));
       }  
       return pPWList;  
   }
   
   /** 
      * Get a list of Project Participant Wrappers
      */
   public List<ProjectParticipantWrapper> getProjectParticipantWrapperList() {
        return this.projParticipantWrapperList;
    }
    
   /**
   * Get new CR Participants list
   */ 
   public List<CR_Participant__c> getNewCrParticipantList() {
        return this.newCrParticipantList;
   }
    
   public Boolean getNextStep() {
       return this.nextStep;
   } 
    
    /** 
    * Build new CR Participants
    */
    public void buildNewCRParticipants() {
        List<CR_Participant__c> crParticipantList = new List<CR_Participant__c>();
        for(ProjectParticipantWrapper ppw : projParticipantWrapperList) {
            if(ppw.selected == true){              
                CR_Participant__c newCRParticipant = new CR_Participant__c();
                newCRParticipant.Account__c =  ppw.projParticipant.Account_Id__c;
                newCRParticipant.Chage_Request__c = this.changeRequest.Id;
                crParticipantList.add(newCRParticipant);    
            }
        }
       this.newCrParticipantList = crParticipantList;
    
       this.nextStep = false;
    }
    
    /**
    * Save new CR Participants into DB & commit
    */
    public PageReference save() {
        try {
           insert this.newCrParticipantList;
        } catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        // After Save, navigate to the default view page:
        return (new ApexPages.StandardController(this.changeRequest)).view();
    }
   /**
   * The class wraps the Project Participant
   */
   public class ProjectParticipantWrapper
    {
        public Project_Participant__c projParticipant {get; set;}
        public Boolean selected {get; set;}
        public ProjectParticipantWrapper(Project_Participant__c pp)
        {
           projParticipant = pp;
           selected = false;
        }
    }
}