src/objects/Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Chage_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>CR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CR_Participant__c.object
<CustomObject>
    <description>Participants for this change -  A subset of Project Participants</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CR Participants</relationshipLabel>
        <relationshipName>CR_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Chage_Request__c</fullName>
        <label>Chage Request</label>
        <referenceTo>Change_Request__c</referenceTo>
        <relationshipLabel>CR Participants</relationshipLabel>
        <relationshipName>CR_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CR Participant</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CR Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>Project information - functions as the root object of all ASN Activities</description>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Participant__c.object
<CustomObject>
    <description>All Vendors participating in this project</description>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project Participants</relationshipLabel>
        <relationshipName>Project_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area_Of_Expertise__c</fullName>
        <label>Area Of Expertise</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <label>Project ID</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Participants</relationshipLabel>
        <relationshipName>Project_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Tier__c</fullName>
        <label>Project Tier</label>
        <picklist>
            <picklistValues>
                <fullName>OEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Participant</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Project Participants</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectParticipantsController.cls
public class ProjectParticipantsController {

    public List<Project_Participant__c> projectParticipants;
    public List<ProjectParticipantWrapper> projectParticipantsWrappers = new List<ProjectParticipantWrapper>();
    public List<Project_Participant__c> seletedParticipants = new List<Project_Participant__c>();
    public Project__c project;
    public Change_Request__c currentCR;   
    
    public ProjectParticipantsController(ApexPages.StandardController controller){
         currentCR = (Change_Request__c)controller.getRecord();
         List<Change_Request__c>   crs = [select cr.project__c from Change_Request__c cr where cr.id=:currentCR.id];
         if(crs.size() > 0){
            Change_Request__c cr = crs.get(0);
            projectParticipants = [select id, name, Account_ID__c,Area_Of_Expertise__c, Project_ID__c, Project_Tier__c
                                     from Project_Participant__c where Project_ID__c =:cr.Project__c];
         }
         
    } 
    
    public List<ProjectParticipantWrapper> getProjectParticipants(){
        for(Project_Participant__c p: projectParticipants ){
            projectParticipantsWrappers.add(new ProjectParticipantWrapper(p) );
        }    
        return projectParticipantsWrappers;    
    }   
    
    public Project__c getProject(){
        return project;
    }
    
    public void addParticipants(){
        filterSelectedParticipants();
        if(seletedParticipants.size() > 0){
            addCRParticipants();        
        }             
    
    }
    
    private void addCRParticipants(){
        for(Project_Participant__c pp: seletedParticipants){
            CR_Participant__c cr_pp = new CR_Participant__c();
            cr_pp.Account__c = pp.Account_ID__c;
            cr_pp.Chage_Request__c = this.currentCR.id ;
            insert cr_pp;    
        }           
    }
    
    private void filterSelectedParticipants(){
        seletedParticipants.clear();
        for(ProjectParticipantWrapper pp: projectParticipantsWrappers){
            if(pp.selected == true){
                seletedParticipants.add(pp.projectParticipant);
            }        
        }            
    
    }
        
    public class ProjectParticipantWrapper {
        public Project_Participant__c projectParticipant{get;set;}
        public Boolean selected{get;set;}
        
        public ProjectParticipantWrapper(Project_Participant__c p)
        {
            projectParticipant = p;
            selected = false;            
        }  
    
    }
     
}