src/objects/Change_Request__c.object
<CustomObject>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>CR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CR_Component__c.object
<CustomObject>
    <description>Major systems and sub system components Impacted by this change. A subset of project components</description>
    <fields>
        <fullName>Change_Request__c</fullName>
        <label>Change Request</label>
        <referenceTo>Change_Request__c</referenceTo>
        <relationshipLabel>CR Components</relationshipLabel>
        <relationshipName>CR_Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Chatter_Group_ID__c</fullName>
        <formula>Project_Component__r.Chatter_Group_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Chatter Group ID</label>
        <type>Text</type>
    </fields>
    <label>CR Component</label>
    <nameField>
        <label>CR Components Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CR Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommonFunctions.cls
/****************************
Created By : Siva Vittala (svittala@csc.com)
Created Date : 1/14/2013
- this class holds all common functions that will be used in this org
- they are declared as public static void functions so can be accessed easily
*****************************/


public class CommonFunctions {
    public static set <ID> getChatterGroupsforCRStep ( ID changeRequestID ) {
    	 set <ID> setChatterGroupnames = new set<ID> ();
         integer i = 0;
         For (CR_Component__c crcomponents:[select chatter_group_ID__C from CR_Component__c where 
                                                      Change_Request__C  = :changeRequestID]) {
             setChatterGroupnames.add(crcomponents.chatter_group_id__c);
             system.debug('Came here WITH '+ crcomponents.chatter_group_id__c);
                                                       
         }
          system.debug ('came out');
          if (setChatterGroupnames.isEmpty()) 
              	return null;
          return setChatterGroupnames ;
    }
public static string getChatterStringforCR ( ID changeRequestID ) {
          string stringName = '';
          For (List <Change_Request__c> licr:[select name from Change_Request__c where 
                                                      ID  = :changeRequestID]) {
                                                          stringName = licr[0].name;   
                                                      }
         return stringName ;
    }
    
}